workspace:
  base: /go
  path: src/github.com/astronomer/astro-cli

pipeline:
  # Build binary
  build:
    image: golang
    commands:
      - make build

  # Test the code
  test:
    image: golang
    commands:
      - make test

  # Cut releases with goreleaser when tagged
  push:
    image: goreleaser/goreleaser:v0.106-cgo
    secrets: [ github_token ]
    commands:
      - git fetch --no-tags origin +refs/tags/${DRONE_TAG}:refs/tags/${DRONE_TAG}
      - goreleaser release --rm-dist
    when:
      event: tag

  notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: platform
    when:
      status: [ failure ]
