# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: astro
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - go mod tidy
release:
  github:
    owner: astronomer
    name: astro-cli
  # If set to auto, will mark the release as not ready for production
  prerelease: true
changelog:
  sort: asc
  use: github
builds:
  - main: main.go
    binary: astro
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - arm64
      - amd64
    goarm:
      - 7
    ldflags: -s -w -X github.com/astronomer/astro-cli/version.CurrVersion={{ .Version }}
brews:
  - tap:
      owner: astronomer
      name: homebrew-tap
    folder: Formula
    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: true
    homepage: https://astronomer.io
    description: To build and run Airflow DAGs locally via docker-compose and deploy DAGs to Astronomer-managed Airflow clusters and interact with the Astronomer API.
    test: |
      system "#{bin}/astro version"
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: binary
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
