ARG PYTHON_MAJOR_MINOR_VERSION="3.9"
ARG PYTHON_BASE_IMAGE="python:${PYTHON_MAJOR_MINOR_VERSION}-slim-bullseye"

FROM ${PYTHON_BASE_IMAGE}

RUN apt-get update -y && apt-get install -y gcc

ARG VERSION=0.0.0

RUN pip install astro-sql-cli==${VERSION}
