// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EnvChecker is an autogenerated mock type for the EnvChecker type
type EnvChecker struct {
	mock.Mock
}

// GetEnvVar provides a mock function with given fields: _a0
func (_m *EnvChecker) GetEnvVar(_a0 string) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewEnvChecker creates a new instance of EnvChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnvChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *EnvChecker {
	mock := &EnvChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
