version: 2.1

executors:
  docker-executor:
    environment:
      GIT_ORG: astronomer
    docker:
      - image: circleci/python:3

parameters:
  cmd-sql-changed:
    type: boolean
    default: false
  sql-changed:
    type: boolean
    default: false

jobs:
  run-e2e-tests:
    working_directory: /go/src/github.com/astronomer/astro-cli
    docker:
      - image: quay.io/astronomer/ap-dind-golang:20.10.21
    steps:
      - run-e2e-tests

commands:
  run-e2e-tests:
    description: "Run e2e tests"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Run e2e tests
          environment:
            HOUSTON_HOST: houston
          command: |
            make e2e_test

workflows:
  run-e2e-tests:
    when:
      or:
        - << pipeline.parameters.cmd-sql-changed >>
        - << pipeline.parameters.sql-changed >>
    jobs:
      - run-e2e-tests
