// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	container "github.com/astronomer/astro-cli/pkg/container"
	mock "github.com/stretchr/testify/mock"
)

// PodmanEngine is an autogenerated mock type for the PodmanEngine type
type PodmanEngine struct {
	mock.Mock
}

// InspectMachine provides a mock function with given fields: name
func (_m *PodmanEngine) InspectMachine(name string) (*container.InspectedMachine, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for InspectMachine")
	}

	var r0 *container.InspectedMachine
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*container.InspectedMachine, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *container.InspectedMachine); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*container.InspectedMachine)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMachines provides a mock function with no fields
func (_m *PodmanEngine) ListMachines() ([]container.ListedMachine, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListMachines")
	}

	var r0 []container.ListedMachine
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]container.ListedMachine, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []container.ListedMachine); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]container.ListedMachine)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPodmanEngine creates a new instance of PodmanEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPodmanEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *PodmanEngine {
	mock := &PodmanEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
