package mocks

import "github.com/stretchr/testify/mock"

// RuntimeChecker is a mock for a GetContainerRuntimeBinary-style func.
// This is a manually created mock, not generated by mockery.
type RuntimeChecker struct {
	mock.Mock
}

func (m *RuntimeChecker) GetContainerRuntimeBinary() (string, error) {
	args := m.Called()
	return args.String(0), args.Error(1)
}
