// Code generated by mockery v2.50.0. DO NOT EDIT.

package astrov1alpha1_mocks

import (
	context "context"

	astrov1alpha1 "github.com/astronomer/astro-cli/astro-client-v1alpha1"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// ClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type ClientWithResponsesInterface struct {
	mock.Mock
}

// CreateAstroIdeProjectWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateAstroIdeProjectWithBodyWithResponse(ctx context.Context, organizationId string, workspaceId string, contentType string, body io.Reader, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateAstroIdeProjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateAstroIdeProjectWithBodyWithResponse")
	}

	var r0 *astrov1alpha1.CreateAstroIdeProjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateAstroIdeProjectResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.CreateAstroIdeProjectResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.CreateAstroIdeProjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateAstroIdeProjectWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateAstroIdeProjectWithResponse(ctx context.Context, organizationId string, workspaceId string, body astrov1alpha1.CreateAstroIdeProjectRequest, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateAstroIdeProjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateAstroIdeProjectWithResponse")
	}

	var r0 *astrov1alpha1.CreateAstroIdeProjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, astrov1alpha1.CreateAstroIdeProjectRequest, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateAstroIdeProjectResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, astrov1alpha1.CreateAstroIdeProjectRequest, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.CreateAstroIdeProjectResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.CreateAstroIdeProjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, astrov1alpha1.CreateAstroIdeProjectRequest, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateAstroIdeSessionWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, projectId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateAstroIdeSessionWithBodyWithResponse(ctx context.Context, organizationId string, workspaceId string, projectId string, contentType string, body io.Reader, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateAstroIdeSessionResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, projectId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateAstroIdeSessionWithBodyWithResponse")
	}

	var r0 *astrov1alpha1.CreateAstroIdeSessionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateAstroIdeSessionResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, projectId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.CreateAstroIdeSessionResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, projectId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.CreateAstroIdeSessionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, projectId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateAstroIdeSessionWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, projectId, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateAstroIdeSessionWithResponse(ctx context.Context, organizationId string, workspaceId string, projectId string, body astrov1alpha1.CreateAstroIdeSessionRequest, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateAstroIdeSessionResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, projectId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateAstroIdeSessionWithResponse")
	}

	var r0 *astrov1alpha1.CreateAstroIdeSessionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, astrov1alpha1.CreateAstroIdeSessionRequest, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateAstroIdeSessionResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, projectId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, astrov1alpha1.CreateAstroIdeSessionRequest, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.CreateAstroIdeSessionResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, projectId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.CreateAstroIdeSessionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, astrov1alpha1.CreateAstroIdeSessionRequest, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, projectId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateBundleWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateBundleWithBodyWithResponse(ctx context.Context, organizationId string, deploymentId string, contentType string, body io.Reader, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateBundleResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateBundleWithBodyWithResponse")
	}

	var r0 *astrov1alpha1.CreateBundleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateBundleResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.CreateBundleResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.CreateBundleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateBundleWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateBundleWithResponse(ctx context.Context, organizationId string, deploymentId string, body astrov1alpha1.CreateBundleRequest, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateBundleResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateBundleWithResponse")
	}

	var r0 *astrov1alpha1.CreateBundleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, astrov1alpha1.CreateBundleRequest, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateBundleResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, astrov1alpha1.CreateBundleRequest, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.CreateBundleResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.CreateBundleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, astrov1alpha1.CreateBundleRequest, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDeployWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateDeployWithBodyWithResponse(ctx context.Context, organizationId string, deploymentId string, contentType string, body io.Reader, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateDeployResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeployWithBodyWithResponse")
	}

	var r0 *astrov1alpha1.CreateDeployResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateDeployResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.CreateDeployResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.CreateDeployResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDeployWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, body, reqEditors
func (_m *ClientWithResponsesInterface) CreateDeployWithResponse(ctx context.Context, organizationId string, deploymentId string, body astrov1alpha1.CreateDeployRequest, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateDeployResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeployWithResponse")
	}

	var r0 *astrov1alpha1.CreateDeployResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, astrov1alpha1.CreateDeployRequest, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.CreateDeployResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, astrov1alpha1.CreateDeployRequest, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.CreateDeployResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.CreateDeployResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, astrov1alpha1.CreateDeployRequest, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBundleWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, bundleId, reqEditors
func (_m *ClientWithResponsesInterface) DeleteBundleWithResponse(ctx context.Context, organizationId string, deploymentId string, bundleId string, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.DeleteBundleResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, bundleId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBundleWithResponse")
	}

	var r0 *astrov1alpha1.DeleteBundleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.DeleteBundleResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, bundleId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.DeleteBundleResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, bundleId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.DeleteBundleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, bundleId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExportAstroIdeSessionTarWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, projectId, sessionId, params, reqEditors
func (_m *ClientWithResponsesInterface) ExportAstroIdeSessionTarWithResponse(ctx context.Context, organizationId string, workspaceId string, projectId string, sessionId string, params *astrov1alpha1.ExportAstroIdeSessionTarParams, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ExportAstroIdeSessionTarResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, projectId, sessionId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExportAstroIdeSessionTarWithResponse")
	}

	var r0 *astrov1alpha1.ExportAstroIdeSessionTarResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *astrov1alpha1.ExportAstroIdeSessionTarParams, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ExportAstroIdeSessionTarResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, projectId, sessionId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *astrov1alpha1.ExportAstroIdeSessionTarParams, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.ExportAstroIdeSessionTarResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, projectId, sessionId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.ExportAstroIdeSessionTarResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *astrov1alpha1.ExportAstroIdeSessionTarParams, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, projectId, sessionId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExportAstroIdeSessionZipWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, projectId, sessionId, params, reqEditors
func (_m *ClientWithResponsesInterface) ExportAstroIdeSessionZipWithResponse(ctx context.Context, organizationId string, workspaceId string, projectId string, sessionId string, params *astrov1alpha1.ExportAstroIdeSessionZipParams, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ExportAstroIdeSessionZipResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, projectId, sessionId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExportAstroIdeSessionZipWithResponse")
	}

	var r0 *astrov1alpha1.ExportAstroIdeSessionZipResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *astrov1alpha1.ExportAstroIdeSessionZipParams, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ExportAstroIdeSessionZipResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, projectId, sessionId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *astrov1alpha1.ExportAstroIdeSessionZipParams, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.ExportAstroIdeSessionZipResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, projectId, sessionId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.ExportAstroIdeSessionZipResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *astrov1alpha1.ExportAstroIdeSessionZipParams, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, projectId, sessionId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAstroIdeProjectWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, projectId, reqEditors
func (_m *ClientWithResponsesInterface) GetAstroIdeProjectWithResponse(ctx context.Context, organizationId string, workspaceId string, projectId string, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.GetAstroIdeProjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, projectId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAstroIdeProjectWithResponse")
	}

	var r0 *astrov1alpha1.GetAstroIdeProjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.GetAstroIdeProjectResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, projectId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.GetAstroIdeProjectResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, projectId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.GetAstroIdeProjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, projectId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBundleWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, bundleId, reqEditors
func (_m *ClientWithResponsesInterface) GetBundleWithResponse(ctx context.Context, organizationId string, deploymentId string, bundleId string, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.GetBundleResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, bundleId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetBundleWithResponse")
	}

	var r0 *astrov1alpha1.GetBundleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.GetBundleResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, bundleId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.GetBundleResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, bundleId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.GetBundleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, bundleId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeployDiffWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, params, reqEditors
func (_m *ClientWithResponsesInterface) GetDeployDiffWithResponse(ctx context.Context, organizationId string, deploymentId string, params *astrov1alpha1.GetDeployDiffParams, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.GetDeployDiffResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetDeployDiffWithResponse")
	}

	var r0 *astrov1alpha1.GetDeployDiffResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *astrov1alpha1.GetDeployDiffParams, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.GetDeployDiffResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *astrov1alpha1.GetDeployDiffParams, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.GetDeployDiffResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.GetDeployDiffResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *astrov1alpha1.GetDeployDiffParams, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeployWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, deployId, params, reqEditors
func (_m *ClientWithResponsesInterface) GetDeployWithResponse(ctx context.Context, organizationId string, deploymentId string, deployId string, params *astrov1alpha1.GetDeployParams, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.GetDeployResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, deployId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetDeployWithResponse")
	}

	var r0 *astrov1alpha1.GetDeployResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *astrov1alpha1.GetDeployParams, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.GetDeployResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, deployId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *astrov1alpha1.GetDeployParams, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.GetDeployResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, deployId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.GetDeployResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *astrov1alpha1.GetDeployParams, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, deployId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImportAstroIdeSessionTarWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, projectId, sessionId, params, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) ImportAstroIdeSessionTarWithBodyWithResponse(ctx context.Context, organizationId string, workspaceId string, projectId string, sessionId string, params *astrov1alpha1.ImportAstroIdeSessionTarParams, contentType string, body io.Reader, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ImportAstroIdeSessionTarResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, projectId, sessionId, params, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ImportAstroIdeSessionTarWithBodyWithResponse")
	}

	var r0 *astrov1alpha1.ImportAstroIdeSessionTarResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *astrov1alpha1.ImportAstroIdeSessionTarParams, string, io.Reader, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ImportAstroIdeSessionTarResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, projectId, sessionId, params, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *astrov1alpha1.ImportAstroIdeSessionTarParams, string, io.Reader, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.ImportAstroIdeSessionTarResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, projectId, sessionId, params, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.ImportAstroIdeSessionTarResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *astrov1alpha1.ImportAstroIdeSessionTarParams, string, io.Reader, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, projectId, sessionId, params, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImportAstroIdeSessionZipWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, projectId, sessionId, params, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) ImportAstroIdeSessionZipWithBodyWithResponse(ctx context.Context, organizationId string, workspaceId string, projectId string, sessionId string, params *astrov1alpha1.ImportAstroIdeSessionZipParams, contentType string, body io.Reader, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ImportAstroIdeSessionZipResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, projectId, sessionId, params, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ImportAstroIdeSessionZipWithBodyWithResponse")
	}

	var r0 *astrov1alpha1.ImportAstroIdeSessionZipResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *astrov1alpha1.ImportAstroIdeSessionZipParams, string, io.Reader, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ImportAstroIdeSessionZipResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, projectId, sessionId, params, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *astrov1alpha1.ImportAstroIdeSessionZipParams, string, io.Reader, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.ImportAstroIdeSessionZipResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, projectId, sessionId, params, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.ImportAstroIdeSessionZipResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *astrov1alpha1.ImportAstroIdeSessionZipParams, string, io.Reader, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, projectId, sessionId, params, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAstroIdeProjectsWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, params, reqEditors
func (_m *ClientWithResponsesInterface) ListAstroIdeProjectsWithResponse(ctx context.Context, organizationId string, workspaceId string, params *astrov1alpha1.ListAstroIdeProjectsParams, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ListAstroIdeProjectsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListAstroIdeProjectsWithResponse")
	}

	var r0 *astrov1alpha1.ListAstroIdeProjectsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *astrov1alpha1.ListAstroIdeProjectsParams, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ListAstroIdeProjectsResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *astrov1alpha1.ListAstroIdeProjectsParams, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.ListAstroIdeProjectsResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.ListAstroIdeProjectsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *astrov1alpha1.ListAstroIdeProjectsParams, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBundlesWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, params, reqEditors
func (_m *ClientWithResponsesInterface) ListBundlesWithResponse(ctx context.Context, organizationId string, deploymentId string, params *astrov1alpha1.ListBundlesParams, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ListBundlesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListBundlesWithResponse")
	}

	var r0 *astrov1alpha1.ListBundlesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *astrov1alpha1.ListBundlesParams, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ListBundlesResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *astrov1alpha1.ListBundlesParams, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.ListBundlesResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.ListBundlesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *astrov1alpha1.ListBundlesParams, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDeployStepLogsWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, deployId, deployStepId, params, reqEditors
func (_m *ClientWithResponsesInterface) ListDeployStepLogsWithResponse(ctx context.Context, organizationId string, deploymentId string, deployId string, deployStepId string, params *astrov1alpha1.ListDeployStepLogsParams, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ListDeployStepLogsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, deployId, deployStepId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListDeployStepLogsWithResponse")
	}

	var r0 *astrov1alpha1.ListDeployStepLogsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *astrov1alpha1.ListDeployStepLogsParams, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ListDeployStepLogsResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, deployId, deployStepId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *astrov1alpha1.ListDeployStepLogsParams, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.ListDeployStepLogsResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, deployId, deployStepId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.ListDeployStepLogsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *astrov1alpha1.ListDeployStepLogsParams, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, deployId, deployStepId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDeployStepsWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, deployId, params, reqEditors
func (_m *ClientWithResponsesInterface) ListDeployStepsWithResponse(ctx context.Context, organizationId string, deploymentId string, deployId string, params *astrov1alpha1.ListDeployStepsParams, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ListDeployStepsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, deployId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListDeployStepsWithResponse")
	}

	var r0 *astrov1alpha1.ListDeployStepsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *astrov1alpha1.ListDeployStepsParams, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ListDeployStepsResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, deployId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *astrov1alpha1.ListDeployStepsParams, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.ListDeployStepsResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, deployId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.ListDeployStepsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *astrov1alpha1.ListDeployStepsParams, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, deployId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDeploysWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, params, reqEditors
func (_m *ClientWithResponsesInterface) ListDeploysWithResponse(ctx context.Context, organizationId string, deploymentId string, params *astrov1alpha1.ListDeploysParams, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ListDeploysResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListDeploysWithResponse")
	}

	var r0 *astrov1alpha1.ListDeploysResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *astrov1alpha1.ListDeploysParams, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.ListDeploysResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *astrov1alpha1.ListDeploysParams, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.ListDeploysResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.ListDeploysResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *astrov1alpha1.ListDeploysParams, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAstroIdeSessionWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, projectId, sessionId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) SaveAstroIdeSessionWithBodyWithResponse(ctx context.Context, organizationId string, workspaceId string, projectId string, sessionId string, contentType string, body io.Reader, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.SaveAstroIdeSessionResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, projectId, sessionId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SaveAstroIdeSessionWithBodyWithResponse")
	}

	var r0 *astrov1alpha1.SaveAstroIdeSessionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.SaveAstroIdeSessionResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, projectId, sessionId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.SaveAstroIdeSessionResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, projectId, sessionId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.SaveAstroIdeSessionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, projectId, sessionId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAstroIdeSessionWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, projectId, sessionId, body, reqEditors
func (_m *ClientWithResponsesInterface) SaveAstroIdeSessionWithResponse(ctx context.Context, organizationId string, workspaceId string, projectId string, sessionId string, body astrov1alpha1.SaveAstroIdeSessionRequest, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.SaveAstroIdeSessionResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, projectId, sessionId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SaveAstroIdeSessionWithResponse")
	}

	var r0 *astrov1alpha1.SaveAstroIdeSessionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, astrov1alpha1.SaveAstroIdeSessionRequest, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.SaveAstroIdeSessionResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, projectId, sessionId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, astrov1alpha1.SaveAstroIdeSessionRequest, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.SaveAstroIdeSessionResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, projectId, sessionId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.SaveAstroIdeSessionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, astrov1alpha1.SaveAstroIdeSessionRequest, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, projectId, sessionId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TriggerGitDeployWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) TriggerGitDeployWithBodyWithResponse(ctx context.Context, organizationId string, deploymentId string, contentType string, body io.Reader, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.TriggerGitDeployResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TriggerGitDeployWithBodyWithResponse")
	}

	var r0 *astrov1alpha1.TriggerGitDeployResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.TriggerGitDeployResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.TriggerGitDeployResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.TriggerGitDeployResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TriggerGitDeployWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, body, reqEditors
func (_m *ClientWithResponsesInterface) TriggerGitDeployWithResponse(ctx context.Context, organizationId string, deploymentId string, body astrov1alpha1.TriggerGitDeployRequest, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.TriggerGitDeployResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TriggerGitDeployWithResponse")
	}

	var r0 *astrov1alpha1.TriggerGitDeployResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, astrov1alpha1.TriggerGitDeployRequest, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.TriggerGitDeployResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, astrov1alpha1.TriggerGitDeployRequest, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.TriggerGitDeployResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.TriggerGitDeployResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, astrov1alpha1.TriggerGitDeployRequest, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAstroIdeSessionWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, projectId, sessionId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateAstroIdeSessionWithBodyWithResponse(ctx context.Context, organizationId string, workspaceId string, projectId string, sessionId string, contentType string, body io.Reader, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.UpdateAstroIdeSessionResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, projectId, sessionId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAstroIdeSessionWithBodyWithResponse")
	}

	var r0 *astrov1alpha1.UpdateAstroIdeSessionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.UpdateAstroIdeSessionResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, projectId, sessionId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.UpdateAstroIdeSessionResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, projectId, sessionId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.UpdateAstroIdeSessionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, projectId, sessionId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAstroIdeSessionWithResponse provides a mock function with given fields: ctx, organizationId, workspaceId, projectId, sessionId, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateAstroIdeSessionWithResponse(ctx context.Context, organizationId string, workspaceId string, projectId string, sessionId string, body astrov1alpha1.UpdateAstroIdeSessionRequest, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.UpdateAstroIdeSessionResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, workspaceId, projectId, sessionId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAstroIdeSessionWithResponse")
	}

	var r0 *astrov1alpha1.UpdateAstroIdeSessionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, astrov1alpha1.UpdateAstroIdeSessionRequest, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.UpdateAstroIdeSessionResponse, error)); ok {
		return rf(ctx, organizationId, workspaceId, projectId, sessionId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, astrov1alpha1.UpdateAstroIdeSessionRequest, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.UpdateAstroIdeSessionResponse); ok {
		r0 = rf(ctx, organizationId, workspaceId, projectId, sessionId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.UpdateAstroIdeSessionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, astrov1alpha1.UpdateAstroIdeSessionRequest, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, workspaceId, projectId, sessionId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBundleWithBodyWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, bundleId, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateBundleWithBodyWithResponse(ctx context.Context, organizationId string, deploymentId string, bundleId string, contentType string, body io.Reader, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.UpdateBundleResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, bundleId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBundleWithBodyWithResponse")
	}

	var r0 *astrov1alpha1.UpdateBundleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.UpdateBundleResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, bundleId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.UpdateBundleResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, bundleId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.UpdateBundleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, io.Reader, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, bundleId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBundleWithResponse provides a mock function with given fields: ctx, organizationId, deploymentId, bundleId, body, reqEditors
func (_m *ClientWithResponsesInterface) UpdateBundleWithResponse(ctx context.Context, organizationId string, deploymentId string, bundleId string, body astrov1alpha1.UpdateBundleRequest, reqEditors ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.UpdateBundleResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, organizationId, deploymentId, bundleId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBundleWithResponse")
	}

	var r0 *astrov1alpha1.UpdateBundleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, astrov1alpha1.UpdateBundleRequest, ...astrov1alpha1.RequestEditorFn) (*astrov1alpha1.UpdateBundleResponse, error)); ok {
		return rf(ctx, organizationId, deploymentId, bundleId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, astrov1alpha1.UpdateBundleRequest, ...astrov1alpha1.RequestEditorFn) *astrov1alpha1.UpdateBundleResponse); ok {
		r0 = rf(ctx, organizationId, deploymentId, bundleId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*astrov1alpha1.UpdateBundleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, astrov1alpha1.UpdateBundleRequest, ...astrov1alpha1.RequestEditorFn) error); ok {
		r1 = rf(ctx, organizationId, deploymentId, bundleId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientWithResponsesInterface creates a new instance of ClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientWithResponsesInterface {
	mock := &ClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
