package cmd

// helpExceptions lists, per rule in helpRules, the commands that failed it
// when the rule was written. The lists only shrink: fix a command's help and
// delete its line, and TestHelpExceptionsOnlyShrink fails on a line left
// behind. Nothing is added here — a new command meets the rules, and an
// existing one that gains a violation is fixed rather than excused.
var helpExceptions = map[string][]string{
	"short": {
		"astro organization audit-logs",
		"astro organization audit-logs export",
	},
	"flag-usage": {
		"astro config",
		"astro deploy",
		"astro deployment create",
		"astro deployment hibernate",
		"astro deployment inspect",
		"astro deployment logs",
		"astro deployment team",
		"astro deployment team add",
		"astro deployment team update",
		"astro deployment token create",
		"astro deployment token organization-token add",
		"astro deployment token organization-token update",
		"astro deployment token update",
		"astro deployment token workspace-token add",
		"astro deployment token workspace-token update",
		"astro deployment update",
		"astro deployment user add",
		"astro deployment user update",
		"astro deployment wake-up",
		"astro deployment worker-queue create",
		"astro deployment worker-queue delete",
		"astro deployment worker-queue update",
		"astro env metrics-export set",
		"astro local check",
		"astro organization audit-logs export",
		"astro organization token",
		"astro organization token create",
		"astro organization token update",
		"astro remote deploy",
		"astro workspace team",
		"astro workspace team add",
		"astro workspace team update",
		"astro workspace token create",
		"astro workspace token update",
		"astro workspace user add",
	},
	"use": {
		"astro api airflow",
		"astro api airflow describe",
		"astro api airflow ls",
		"astro api cloud",
		"astro api cloud describe",
		"astro api cloud ls",
		"astro api registry",
		"astro api registry describe",
		"astro api registry ls",
		"astro config get",
		"astro config set",
		"astro context delete",
		"astro context switch",
		"astro dbt cleanup",
		"astro dbt delete",
		"astro dbt deploy",
		"astro deploy",
		"astro deployment bundle delete",
		"astro deployment bundle update",
		"astro deployment delete",
		"astro deployment hibernate",
		"astro deployment logs",
		"astro deployment service-account delete",
		"astro deployment team add",
		"astro deployment team remove",
		"astro deployment team update",
		"astro deployment update",
		"astro deployment user add",
		"astro deployment user remove",
		"astro deployment user update",
		"astro deployment variable create",
		"astro deployment variable update",
		"astro deployment wake-up",
		"astro env airflow-variable delete",
		"astro env airflow-variable get",
		"astro env airflow-variable set",
		"astro env connection delete",
		"astro env connection get",
		"astro env connection set",
		"astro env metrics-export delete",
		"astro env metrics-export get",
		"astro env metrics-export set",
		"astro env variable delete",
		"astro env variable get",
		"astro env variable set",
		"astro init",
		"astro link add",
		"astro local api",
		"astro local api ls",
		"astro local env airflow-variable declare",
		"astro local env airflow-variable delete",
		"astro local env airflow-variable get",
		"astro local env airflow-variable link",
		"astro local env airflow-variable set",
		"astro local env airflow-variable undeclare",
		"astro local env airflow-variable unlink",
		"astro local env connection declare",
		"astro local env connection delete",
		"astro local env connection get",
		"astro local env connection link",
		"astro local env connection set",
		"astro local env connection undeclare",
		"astro local env connection unlink",
		"astro local run",
		"astro local upgrade airflow",
		"astro organization switch",
		"astro organization team delete",
		"astro organization team update",
		"astro organization user invite",
		"astro organization user update",
		"astro otto",
		"astro package",
		"astro team get",
		"astro team update",
		"astro workspace delete",
		"astro workspace service-account delete",
		"astro workspace switch",
		"astro workspace team add",
		"astro workspace team remove",
		"astro workspace team update",
		"astro workspace update",
		"astro workspace user add",
		"astro workspace user remove",
		"astro workspace user update",
	},
	"example": {
		"astro af assets events",
		"astro af assets list",
		"astro af assets triggers",
		"astro af config",
		"astro af connections get",
		"astro af connections list",
		"astro af dags errors",
		"astro af dags explore",
		"astro af dags get",
		"astro af dags list",
		"astro af dags pause",
		"astro af dags source",
		"astro af dags stats",
		"astro af dags unpause",
		"astro af dags warnings",
		"astro af health",
		"astro af plugins",
		"astro af pools get",
		"astro af pools list",
		"astro af providers",
		"astro af runs clear",
		"astro af runs delete",
		"astro af runs diagnose",
		"astro af runs get",
		"astro af runs list",
		"astro af runs tasks",
		"astro af runs trigger",
		"astro af runs trigger-wait",
		"astro af tasks clear",
		"astro af tasks get",
		"astro af tasks instance",
		"astro af tasks list",
		"astro af tasks logs",
		"astro af variables get",
		"astro af variables list",
		"astro af version",
		"astro auth login",
		"astro auth logout",
		"astro auth token",
		"astro config list",
		"astro context delete",
		"astro context list",
		"astro context switch",
		"astro dbt cleanup",
		"astro deployment delete",
		"astro deployment list",
		"astro deployment logs scheduler",
		"astro deployment logs triggerer",
		"astro deployment logs webserver",
		"astro deployment logs workers",
		"astro deployment update",
		"astro env airflow-variable delete",
		"astro env airflow-variable get",
		"astro env airflow-variable link delete",
		"astro env airflow-variable link list",
		"astro env airflow-variable link set",
		"astro env airflow-variable list",
		"astro env airflow-variable set",
		"astro env connection delete",
		"astro env connection get",
		"astro env connection link delete",
		"astro env connection link list",
		"astro env connection link set",
		"astro env connection list",
		"astro env connection set",
		"astro env list",
		"astro env metrics-export delete",
		"astro env metrics-export get",
		"astro env metrics-export list",
		"astro env metrics-export set",
		"astro env variable delete",
		"astro env variable export",
		"astro env variable get",
		"astro env variable link delete",
		"astro env variable link list",
		"astro env variable link set",
		"astro env variable list",
		"astro env variable set",
		"astro init",
		"astro local af assets events",
		"astro local af assets list",
		"astro local af assets triggers",
		"astro local af config",
		"astro local af connections get",
		"astro local af connections list",
		"astro local af dags errors",
		"astro local af dags explore",
		"astro local af dags get",
		"astro local af dags list",
		"astro local af dags pause",
		"astro local af dags source",
		"astro local af dags stats",
		"astro local af dags unpause",
		"astro local af dags warnings",
		"astro local af health",
		"astro local af plugins",
		"astro local af pools get",
		"astro local af pools list",
		"astro local af providers",
		"astro local af runs clear",
		"astro local af runs delete",
		"astro local af runs diagnose",
		"astro local af runs get",
		"astro local af runs list",
		"astro local af runs tasks",
		"astro local af runs trigger",
		"astro local af runs trigger-wait",
		"astro local af tasks clear",
		"astro local af tasks get",
		"astro local af tasks instance",
		"astro local af tasks list",
		"astro local af tasks logs",
		"astro local af variables get",
		"astro local af variables list",
		"astro local af version",
		"astro local check",
		"astro local env airflow-variable declare",
		"astro local env airflow-variable delete",
		"astro local env airflow-variable get",
		"astro local env airflow-variable list",
		"astro local env airflow-variable set",
		"astro local env airflow-variable undeclare",
		"astro local env connection declare",
		"astro local env connection delete",
		"astro local env connection get",
		"astro local env connection list",
		"astro local env connection set",
		"astro local env connection undeclare",
		"astro local env list",
		"astro local env variable declare",
		"astro local env variable delete",
		"astro local env variable get",
		"astro local env variable list",
		"astro local env variable set",
		"astro local env variable undeclare",
		"astro local list",
		"astro local logs",
		"astro local open",
		"astro local reset",
		"astro local restart",
		"astro local run",
		"astro local shell",
		"astro local start",
		"astro local status",
		"astro local stop",
		"astro login",
		"astro logout",
		"astro otto",
		"astro package",
		"astro team get",
		"astro team list",
		"astro team update",
		"astro telemetry disable",
		"astro telemetry enable",
		"astro version",
		"astro workspace create",
		"astro workspace list",
		"astro workspace switch",
		"astro workspace token organization-token add",
		"astro workspace token organization-token list",
		"astro workspace token organization-token remove",
		"astro workspace token organization-token update",
		"astro workspace user add",
		"astro workspace user list",
		"astro workspace user update",
	},
	"example-style": {
		"astro config get",
		"astro config set",
		"astro dbt delete",
		"astro dbt deploy",
		"astro deploy",
		"astro deployment airflow upgrade",
		"astro deployment create",
		"astro deployment delete",
		"astro deployment hibernate",
		"astro deployment inspect",
		"astro deployment logs",
		"astro deployment runtime migrate",
		"astro deployment runtime upgrade",
		"astro deployment service-account create",
		"astro deployment service-account delete",
		"astro deployment service-account list",
		"astro deployment team add",
		"astro deployment team list",
		"astro deployment team remove",
		"astro deployment team update",
		"astro deployment token create",
		"astro deployment token delete",
		"astro deployment token list",
		"astro deployment token organization-token add",
		"astro deployment token organization-token list",
		"astro deployment token organization-token remove",
		"astro deployment token organization-token update",
		"astro deployment token rotate",
		"astro deployment token update",
		"astro deployment token workspace-token add",
		"astro deployment token workspace-token list",
		"astro deployment token workspace-token remove",
		"astro deployment token workspace-token update",
		"astro deployment update",
		"astro deployment user add",
		"astro deployment user list",
		"astro deployment user remove",
		"astro deployment user update",
		"astro deployment variable create",
		"astro deployment variable list",
		"astro deployment variable update",
		"astro deployment wake-up",
		"astro deployment worker-queue create",
		"astro deployment worker-queue delete",
		"astro deployment worker-queue update",
		"astro ide project export",
		"astro ide project import",
		"astro ide project list",
		"astro organization audit-logs export",
		"astro organization role list",
		"astro organization switch",
		"astro organization team create",
		"astro organization team delete",
		"astro organization team update",
		"astro organization team user add",
		"astro organization team user list",
		"astro organization team user remove",
		"astro organization token create",
		"astro organization token delete",
		"astro organization token list",
		"astro organization token roles",
		"astro organization token rotate",
		"astro organization token update",
		"astro organization user invite",
		"astro organization user update",
		"astro remote deploy",
		"astro user create",
		"astro workspace create",
		"astro workspace delete",
		"astro workspace service-account create",
		"astro workspace service-account delete",
		"astro workspace service-account list",
		"astro workspace switch",
		"astro workspace team add",
		"astro workspace team list",
		"astro workspace team remove",
		"astro workspace team update",
		"astro workspace token add",
		"astro workspace token create",
		"astro workspace token delete",
		"astro workspace token list",
		"astro workspace token rotate",
		"astro workspace token update",
		"astro workspace update",
		"astro workspace user add",
		"astro workspace user remove",
		"astro workspace user update",
	},
}
