package cmd

// helpExceptions lists, per rule in helpRules, the commands that failed it
// when the rule was written. The lists only shrink: fix a command's help and
// delete its line, and TestHelpExceptionsOnlyShrink fails on a line left
// behind. Nothing is added here — a new command meets the rules, and an
// existing one that gains a violation is fixed rather than excused.
var helpExceptions = map[string][]string{
	"short": {
		"astro organization audit-logs",
		"astro organization audit-logs export",
	},
	"flag-usage": {
		"astro organization audit-logs export",
		"astro organization token",
		"astro organization token create",
		"astro organization token update",
		"astro workspace team",
		"astro workspace team add",
		"astro workspace team update",
		"astro workspace token create",
		"astro workspace token update",
		"astro workspace user add",
	},
	"use": {
		"astro link add",
		"astro organization switch",
		"astro organization team delete",
		"astro organization team update",
		"astro organization user invite",
		"astro organization user update",
		"astro team get",
		"astro team update",
		"astro workspace delete",
		"astro workspace service-account delete",
		"astro workspace switch",
		"astro workspace team add",
		"astro workspace team remove",
		"astro workspace team update",
		"astro workspace update",
		"astro workspace user add",
		"astro workspace user remove",
		"astro workspace user update",
	},
	"example": {
		"astro team get",
		"astro team list",
		"astro team update",
		"astro workspace create",
		"astro workspace list",
		"astro workspace switch",
		"astro workspace token organization-token add",
		"astro workspace token organization-token list",
		"astro workspace token organization-token remove",
		"astro workspace token organization-token update",
		"astro workspace user add",
		"astro workspace user list",
		"astro workspace user update",
	},
	"example-style": {
		"astro organization audit-logs export",
		"astro organization role list",
		"astro organization switch",
		"astro organization team create",
		"astro organization team delete",
		"astro organization team update",
		"astro organization team user add",
		"astro organization team user list",
		"astro organization team user remove",
		"astro organization token create",
		"astro organization token delete",
		"astro organization token list",
		"astro organization token roles",
		"astro organization token rotate",
		"astro organization token update",
		"astro organization user invite",
		"astro organization user update",
		"astro user create",
		"astro workspace create",
		"astro workspace delete",
		"astro workspace service-account create",
		"astro workspace service-account delete",
		"astro workspace service-account list",
		"astro workspace switch",
		"astro workspace team add",
		"astro workspace team list",
		"astro workspace team remove",
		"astro workspace team update",
		"astro workspace token add",
		"astro workspace token create",
		"astro workspace token delete",
		"astro workspace token list",
		"astro workspace token rotate",
		"astro workspace token update",
		"astro workspace update",
		"astro workspace user add",
		"astro workspace user remove",
		"astro workspace user update",
	},
}
