package cmd

// helpExceptions lists, per rule in helpRules, the commands that failed it
// when the rule was written. The lists only shrink: fix a command's help and
// delete its line, and TestHelpExceptionsOnlyShrink fails on a line left
// behind. Nothing is added here — a new command meets the rules, and an
// existing one that gains a violation is fixed rather than excused.
var helpExceptions = map[string][]string{
	"short": {
		"astro organization audit-logs",
		"astro organization audit-logs export",
	},
	"flag-usage": {
		"astro config",
		"astro deploy",
		"astro env metrics-export set",
		"astro organization audit-logs export",
		"astro organization token",
		"astro organization token create",
		"astro organization token update",
		"astro remote deploy",
		"astro workspace team",
		"astro workspace team add",
		"astro workspace team update",
		"astro workspace token create",
		"astro workspace token update",
		"astro workspace user add",
	},
	"use": {
		"astro api airflow",
		"astro api airflow describe",
		"astro api airflow ls",
		"astro api cloud",
		"astro api cloud describe",
		"astro api cloud ls",
		"astro api registry",
		"astro api registry describe",
		"astro api registry ls",
		"astro config get",
		"astro config set",
		"astro context delete",
		"astro context switch",
		"astro dbt cleanup",
		"astro dbt delete",
		"astro dbt deploy",
		"astro deploy",
		"astro env airflow-variable delete",
		"astro env airflow-variable get",
		"astro env airflow-variable set",
		"astro env connection delete",
		"astro env connection get",
		"astro env connection set",
		"astro env metrics-export delete",
		"astro env metrics-export get",
		"astro env metrics-export set",
		"astro env variable delete",
		"astro env variable get",
		"astro env variable set",
		"astro link add",
		"astro organization switch",
		"astro organization team delete",
		"astro organization team update",
		"astro organization user invite",
		"astro organization user update",
		"astro otto",
		"astro team get",
		"astro team update",
		"astro workspace delete",
		"astro workspace service-account delete",
		"astro workspace switch",
		"astro workspace team add",
		"astro workspace team remove",
		"astro workspace team update",
		"astro workspace update",
		"astro workspace user add",
		"astro workspace user remove",
		"astro workspace user update",
	},
	"example": {
		"astro auth login",
		"astro auth logout",
		"astro auth token",
		"astro config list",
		"astro context delete",
		"astro context list",
		"astro context switch",
		"astro dbt cleanup",
		"astro env airflow-variable delete",
		"astro env airflow-variable get",
		"astro env airflow-variable link delete",
		"astro env airflow-variable link list",
		"astro env airflow-variable link set",
		"astro env airflow-variable list",
		"astro env airflow-variable set",
		"astro env connection delete",
		"astro env connection get",
		"astro env connection link delete",
		"astro env connection link list",
		"astro env connection link set",
		"astro env connection list",
		"astro env connection set",
		"astro env list",
		"astro env metrics-export delete",
		"astro env metrics-export get",
		"astro env metrics-export list",
		"astro env metrics-export set",
		"astro env variable delete",
		"astro env variable export",
		"astro env variable get",
		"astro env variable link delete",
		"astro env variable link list",
		"astro env variable link set",
		"astro env variable list",
		"astro env variable set",
		"astro login",
		"astro logout",
		"astro otto",
		"astro team get",
		"astro team list",
		"astro team update",
		"astro telemetry disable",
		"astro telemetry enable",
		"astro version",
		"astro workspace create",
		"astro workspace list",
		"astro workspace switch",
		"astro workspace token organization-token add",
		"astro workspace token organization-token list",
		"astro workspace token organization-token remove",
		"astro workspace token organization-token update",
		"astro workspace user add",
		"astro workspace user list",
		"astro workspace user update",
	},
	"example-style": {
		"astro config get",
		"astro config set",
		"astro dbt delete",
		"astro dbt deploy",
		"astro deploy",
		"astro ide project export",
		"astro ide project import",
		"astro ide project list",
		"astro organization audit-logs export",
		"astro organization role list",
		"astro organization switch",
		"astro organization team create",
		"astro organization team delete",
		"astro organization team update",
		"astro organization team user add",
		"astro organization team user list",
		"astro organization team user remove",
		"astro organization token create",
		"astro organization token delete",
		"astro organization token list",
		"astro organization token roles",
		"astro organization token rotate",
		"astro organization token update",
		"astro organization user invite",
		"astro organization user update",
		"astro remote deploy",
		"astro user create",
		"astro workspace create",
		"astro workspace delete",
		"astro workspace service-account create",
		"astro workspace service-account delete",
		"astro workspace service-account list",
		"astro workspace switch",
		"astro workspace team add",
		"astro workspace team list",
		"astro workspace team remove",
		"astro workspace team update",
		"astro workspace token add",
		"astro workspace token create",
		"astro workspace token delete",
		"astro workspace token list",
		"astro workspace token rotate",
		"astro workspace token update",
		"astro workspace update",
		"astro workspace user add",
		"astro workspace user remove",
		"astro workspace user update",
	},
}
