// Code generated by mockery v2.50.0. DO NOT EDIT.

package astrocore_mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// BundleFilesStreamClient is an autogenerated mock type for the BundleFilesStreamClient type
type BundleFilesStreamClient struct {
	mock.Mock
}

// DownloadBundleArchive provides a mock function with given fields: ctx, orgID, deploymentID
func (_m *BundleFilesStreamClient) DownloadBundleArchive(ctx context.Context, orgID string, deploymentID string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, orgID, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for DownloadBundleArchive")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (io.ReadCloser, error)); ok {
		return rf(ctx, orgID, deploymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) io.ReadCloser); ok {
		r0 = rf(ctx, orgID, deploymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orgID, deploymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DownloadBundleFile provides a mock function with given fields: ctx, orgID, deploymentID, filePath
func (_m *BundleFilesStreamClient) DownloadBundleFile(ctx context.Context, orgID string, deploymentID string, filePath string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, orgID, deploymentID, filePath)

	if len(ret) == 0 {
		panic("no return value specified for DownloadBundleFile")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (io.ReadCloser, error)); ok {
		return rf(ctx, orgID, deploymentID, filePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) io.ReadCloser); ok {
		r0 = rf(ctx, orgID, deploymentID, filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, orgID, deploymentID, filePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadBundleArchive provides a mock function with given fields: ctx, orgID, deploymentID, body, contentLength, overwrite, targetPath
func (_m *BundleFilesStreamClient) UploadBundleArchive(ctx context.Context, orgID string, deploymentID string, body io.Reader, contentLength int64, overwrite bool, targetPath string) error {
	ret := _m.Called(ctx, orgID, deploymentID, body, contentLength, overwrite, targetPath)

	if len(ret) == 0 {
		panic("no return value specified for UploadBundleArchive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, int64, bool, string) error); ok {
		r0 = rf(ctx, orgID, deploymentID, body, contentLength, overwrite, targetPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadBundleFile provides a mock function with given fields: ctx, orgID, deploymentID, filePath, body, contentLength
func (_m *BundleFilesStreamClient) UploadBundleFile(ctx context.Context, orgID string, deploymentID string, filePath string, body io.Reader, contentLength int64) error {
	ret := _m.Called(ctx, orgID, deploymentID, filePath, body, contentLength)

	if len(ret) == 0 {
		panic("no return value specified for UploadBundleFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader, int64) error); ok {
		r0 = rf(ctx, orgID, deploymentID, filePath, body, contentLength)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBundleFilesStreamClient creates a new instance of BundleFilesStreamClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBundleFilesStreamClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BundleFilesStreamClient {
	mock := &BundleFilesStreamClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
