// Code generated by mockery v2.32.0. DO NOT EDIT.

package runtimetemplateclient_mocks

import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// DownloadAndExtractTemplate provides a mock function with given fields: templateDir, destDir
func (_m *Client) DownloadAndExtractTemplate(templateDir string, destDir string) error {
	ret := _m.Called(templateDir, destDir)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(templateDir, destDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
