// Code generated by mockery v2.50.0. DO NOT EDIT.

package azure_mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Azure is an autogenerated mock type for the Azure type
type Azure struct {
	mock.Mock
}

// Upload provides a mock function with given fields: sasLink, dagFileReader
func (_m *Azure) Upload(sasLink string, dagFileReader io.Reader) (string, error) {
	ret := _m.Called(sasLink, dagFileReader)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, io.Reader) (string, error)); ok {
		return rf(sasLink, dagFileReader)
	}
	if rf, ok := ret.Get(0).(func(string, io.Reader) string); ok {
		r0 = rf(sasLink, dagFileReader)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, io.Reader) error); ok {
		r1 = rf(sasLink, dagFileReader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAzure creates a new instance of Azure. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAzure(t interface {
	mock.TestingT
	Cleanup(func())
}) *Azure {
	mock := &Azure{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
